### ISSUE TITLE
plotCutoff parameter in fcPlot

### ISSUE THREAD

**Issue by elisabettasciacca** [KatrionaGoldmann/glmmSeq#13]
hi Kat,

I don't know if it's me, but the role of the `plotCutoff ` option in the `fcPlot` function doesn't  look to be very clear . 
I think it would be good if you can explain better what it is meant for.
I was trying to remove all the dots that are below my significance threshold (q < 0.05), I thought this option was able to help me but maybe it's not the case.

**Comment by KatrionaGoldmann** [comment]
Hi Elisabetta, 

I've tried to clear this up in the latest release. The cutoff acts across all p-values (standard as well as interaction) so genes are excluded if _all_ terms are considered insignificant. In order to exclude genes by a specific p or q-value you can intercept the glmmSeq object, for example: 

```
# subset to only genes where p_timepoint <= 0.01
results@countdata = results@countdata[results@stats$P_Timepoint <= 0.01, ]
results@predict = results@predict[results@stats$P_Timepoint <= 0.01, ]
results@stats = results@stats[results@stats$P_Timepoint <= 0.01, ]

fcPlot(glmmResult=results,
       x1Label="Timepoint",
       x2Label="EULAR_6m",
       x2Values=c("Good responder", "Non responder"),
       pCutoff=0.1,
       labels=labels,
       useAdjusted = FALSE,
       plotCutoff = 0.1)
```
