### ISSUE TITLE
pairedPlot error using GlmmSeq object with covariates

### ISSUE THREAD

**Issue by kew24** [KatrionaGoldmann/glmmSeq#18]
Thanks for your work on this package!

When using an object of class `GlmmSeq` in `pairedPlot()`, if additional covariates are included the model, the `pairedPlot()` function does not work due to the code shown below. The vignette shows an example with an interaction and a random effect (` ~ Timepoint * EULAR_6m + (1 | PATID)`). However, if other covariates (e.g., gender) are in the model, the following error occurs. 

Is there a reason why you've chosen to throw an error here (e.g. plotting difficulty, statistical messiness), and is there a workaround if other covariates are in the model? 

relevant code: lines 133-136 of pairedPlots.R
```r
if(ncol(glmmResult@modelData) != 2){
  stop(
    paste("These plots only work for interactions between two variable.",
          "Therefore nrow(glmmResult@modelData) should be 2."))
```

Thanks!

**Comment by KatrionaGoldmann** [comment]
Hi @kew24, thanks for the issue! apologies for the delay in responding. The reason for this was due to the structure of the modelData when multiple variables are included since the values become non-unique for x1 and x2. 

I can look into alternative plots, would you be interested in visualising the additional variable (e.g. gender) as well (e.g. by faceting or multiple linetypes/colours etc). 

Or are you more interested in keeping the same plot but adding additional stats to the top?

**Comment by kew24** [comment]
Thanks for responding @KatrionaGoldmann! For now, I'm simply interested in visualizing my interaction variables (analogous to Timepoint and EULAR_6m), just like the original pariedPlot -- although options for faceting could be nice further down the road, too.

I've been making edits to pairedPlot to add some flexibility (for additional covariates and more than 2 timepoints). The only issue I'm running into now is calculating the y & CIs in `df_mean`. Ideally I'd want to average over the levels of our added covariates, similar to how `emmeans` does this when not explicitly giving it a variable to condition on. 

My current attempt to do this simply averages all of the resulting columns in `df_mean` that pertain to each combination of the interaction variables (`x1Values` and `x2Values` -- basically `outLabels`). However, for some reason, this seems to severely overestimate the predictions and CIs, which I'm guessing is due to the way glmmSeq takes every possible combination of variable levels in the model and predicts on these (regardless of how likely these combinations are to occur). I think we'd need some sort of weighted average instead, based on the expected/true prevalence of various covariates co-occurring. But -- that got a bit too complex, so I'm trying to think of other ways to get around this problem.

I'd be curious to hear your thoughts on this, and if you have any other ideas on how to best average over levels of a covariate. Perhaps your idea of keeping this information in and displaying it in different colors could be a good workaround.

I can also fork the repo & create a pull request with my changes to see what you think so far.

Thanks again!

**Comment by myles-lewis** [comment]
Hi @kew24,

The averaging of the columns in df_mean will overestimate the CIs because of the random effects (REs). I have looked into `emmeans` and this is a great package. I will work on a system of adapting the code to be able to work more easily with `emmeans` especially for plotting. Storing each fitted `glmer` or `lmer` model for every gene consumes a lot of memory and time. But we could fit a fresh (identical) model for plotting purposes via `emmeans` for a single gene.

`pairedPlot` should cope automatically with multiple time points. But it does expect this fixed format of 1 time variable and 1 other variable of interest. `emmeans` is much more flexible. I will try to provide an interface function.

Bw, Myles

**Comment by myles-lewis** [comment]
Hi @kew24,

The new version (currently 0.5.1) has a new function called `glmmRefit()` which allows fitting of a single GLMM or LMM to enable plotting of fitted models via the `emmeans` package. `pairedPlot()` has been deprecated and merged into `modelPlot()` and `ggmodelPlot()`, i.e. plotting the model estimated marginal means as well as the underlying data, with the option of displaying either. `modelPlot()` and `ggmodelPlot()` have been updated so that they can show the time var alone. I will work on adding faceting to `ggmodelPlot()` in future versions, but in the meantime I recommend you use `emmeans` since its plotting is more mature and more flexible.

Bw, Myles
